# Generated by Django 4.0.5 on 2023-02-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tagline',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
