# Generated by Django 4.0.5 on 2023-02-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_tagline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tagline',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
