# Generated by Django 4.1.6 on 2023-03-05 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.CharField(default=-1, max_length=20),
            preserve_default=False,
        ),
    ]
