# Generated by Django 4.1.6 on 2023-03-05 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
