# Generated by Django 4.0.5 on 2023-02-20 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placementStories', '0003_alter_story_text_question_answers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answers',
            new_name='answer',
        ),
    ]
