# Generated by Django 4.1.6 on 2023-04-06 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='classes',
            new_name='ClassRoom',
        ),
    ]
